### ISSUE TITLE
Helpers aren't loaded

### ISSUE THREAD

**Issue by rchampourlier** [sporkrb/spork-rails#6] opened 2012-04-03 15:05 UTC
**I'm running some tests with Cucumber through spork with spork-rails 3.2.0 and spork 1.0.0rc2 and I cannot get my helper methods to be loaded.**
- Ruby is `ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.1.0]`
- Rails is `3.0.12`

Everything is fine when:
- I run with spork 1.0.0rc2 only (removing spork-rails from the Gemfile). This is not acceptable since spork does not reload the controllers anymore.
- I run without spork at all.

I'm using many gems (Devise, FactoryGirl, Mongoid - also using ActiveRecord), but not ActiveAdmin. I say this because this issue is like the [issue #109 on spork](https://github.com/sporkrb/spork/issues/109). **Nothing from this issue could help me, and now that `spork-rails` has been extracted, it seemed to me the issue belonged here.**

Here is a [gist](https://gist.github.com/2292731) of my configuration. For now, I will be running my features without Spork...

**Comment by rchampourlier** [comment] 2012-04-23 12:18
Same issue when running integration/request specs within RSpec.

Any help? Thanks in advance... to anyone!

**Comment by mreinsch** [comment] 2012-05-02 02:10
Same here. Seems any helpers coming from gems are not being loaded. All is fine when running tests directly...

**Comment by mreinsch** [comment] 2012-05-02 03:58
ok, actually all helpers are not being available in the tests. If I disable the handling for reloading helpers (as in my branch at https://github.com/mreinsch/spork-rails), the helpers are fine.

Could this be an ordering issue where the helpers are somehow cleared again after getting loaded? I could confirm that they are being added, just not sure what happens then before the tests start.

**Comment by evgenyneu** [comment] 2012-06-05 11:12
I have the same problem. Devise helper `devise_error_messages!` is not available in tests and shows error:

```
undefined method `devise_error_messages!'
```

Devise includes this helper into DeviseController with method `helper DeviseHelper` (app/controllers/devise_controller.rb). spork-rails changes the `helper` method in `app_framework/rails.rb`, line 61. It them runs `add_template_helper(mod)` which does not work for DeviseHelper.

To make the Devise helper work, I needed to add the following code to `spec_helper.rb`

```
class DeviseController
  include DeviseHelper
  include ActionView::Helpers::TagHelper
  helper_method :devise_error_messages!
  helper_method :content_tag
end
```

**Comment by lidaobing** [comment] 2012-06-27 05:12
same issue as https://github.com/sporkrb/spork/issues/109

**Comment by tom-kuca** [comment] 2012-09-07 10:44
Same issue with rails 3.2.8, spork 1.0.0rc3, spork-rails 3.2.0. I spent a few time trying to find out where the things went wrong.

Given a simple gem which defines module `ApplicationHelper` with method `hello_world` and given an application _without_ `ApplicationHelper` in `app/helpers/`, the spec which tries to render view with `hello_world` method fails with undefined method `hello_world`.

###### Notes:
- the gem does not include `ApplicationHelper` anywhere, it just defines it in it's `lib` directory
- the spec passes without spork
- the spec passes if there is even empty `ApplicationHelper` in `app/helpers/application_helper.rb`

I believe the problem is in the method `helper`. The spork version will raise an exception  if `
 ::ActiveSupport::Dependencies.search_for_file(filename)` doesn't find the helper file in `app/helpers` while the original one from `ruby AbstractController` fallbacks to `require 'application_helper'`. Since the gem's `lib` directory is in `$LOAD_PATH`, the module from gem is loaded and the `helper` loads the helper methods.

###### Notes
- maybe the gem should add helper's in some other way
- when inheriting from ApplicationControlloer, the  method `helper` is called with  `ApplicationHelper` as an argument

**Comment by pedrobachiega** [comment] 2012-09-11 17:20
same problem to load helpers here...

if I include each helper, it works, but I would know some clean way to do this

``` ruby
Spork.prefork do
  ENV["RAILS_ENV"] ||= 'test'
  require File.expand_path("../../config/environment", __FILE__)
  require 'rspec/rails'
  require 'shoulda/matchers/integrations/rspec'
  include ApplicationHelper
  include GraphicsHelper
  ...
```

**Comment by vascoosx** [comment] 2012-10-07 06:51
I had the same problem. The only workaround I found was calling those helpers with 

``` ruby
ApplicationController.helpers.<helper name> 
```

**Comment by fweep** [comment] 2012-11-23 04:42
This problem still exists.  I was digging around the source, and I think it has something to do with how spork-rails overrides the AbstractController::Helpers::ClassMethods#helper(), but I'm not sure, as I wasn't able to fix it there.  I did figure out that if I just use spork instead of spork-rails, everything seems to work fine.  I'm wondering what the benefit of spork-rails is.  It doesn't do too much; disables eager loading (not sure why), loads some Rails environment stuff, and overrides #helper().  Everything runs nice and fast with just plain spork, though.

**Comment by krishnasrihari** [comment] 2012-12-06 07:48
I got same issue in spork, I tried in spork-rails gem but same issue. Is there any progress for this issue?

**Comment by krishnasrihari** [comment] 2012-12-06 10:05
To fix this issue add these below lines in Spork.prefork block

```
full_names = Dir["#{Rails.root}/app/helpers/*.rb"]
full_names.collect do |full_name|
    include Object.const_get(File.basename(full_name,'.rb').camelize)
end
```

**Comment by pedrobachiega** [comment] 2012-12-06 21:35
@krishnasrihari this works for me! thanks!

**Comment by eostrom** [comment] 2012-12-11 05:19
@krishnasrihari's workaround looks like it will cover helpers defined within the application, but not helpers in gems. It could be adapted, but really, my Spork configuration shouldn't have to go find all the gems with helpers in them.

I'm inclined to agree with @fweep's hunch that it has to do with the `#helper` override. The pull request for sporkrb/spork#140 fixes this problem by removing the override completely, but it was rejected because that caused other problems. (I.e., that code is there for a reason!)

The `#helper` override was added in sporkrb/spork@d08fee3b64d94c43a9f6347fb89e3e8f2311f691. It looks like the goal was to ensure helpers are reloaded in each run, so you don't have to restart spork. Good idea, but is it somehow preventing helpers in gems from being loaded at all?

Oh hey, it looks like @tom-kuca's analysis has more details on this. Good job! Now all we need is a fix and an integration test.

**Comment by nozpheratu** [comment] 2013-02-13 20:20
I'm also having this problem...

**Comment by johnnyshields** [comment] 2013-02-14 05:01
Me too. +1

@krishnasrihari's fix worked for me.

**Comment by nozpheratu** [comment] 2013-02-14 18:02
The fixed that worked for me was:

``` ruby
AbstractController::Helpers::ClassMethods.module_eval do def helper(*args, &block); modules_for_helpers(args).each {|mod| add_template_helper(mod)}; _helpers.module_eval(&block) if block_given?; end end
```

I don't remember where I got this code, sorry for not giving any credit.

**Comment by marcusg** [comment] 2013-04-18 19:14
any progress here?

**Comment by yannp** [comment] 2013-06-27 08:14
+1

**Comment by epylinkn** [comment] 2013-08-03 02:57
+1

**Comment by sahilm** [comment] 2013-09-14 12:40
Closing old bugs. If you think this issue needs resolution please open a new issue.

**Closed as completed by sahilm** 2013-09-14 12:40 UTC

**Comment by johnnyshields** [comment] 2013-10-14 21:47
@sahilm why did you close this issue? It's still not fixed, despite many people requesting it.

**Comment by marcusg** [comment] 2013-10-29 17:06
@sahilm can you reopen this, because it is not fixed. thanks!

**Comment by brandonparsons** [comment] 2013-11-18 13:26
Yes this is still borked.

**Comment by jpemberthy** [comment] 2013-11-26 01:50
+1

**Comment by jalada** [comment] 2013-12-03 11:03
:+1:

**Comment by daniel-g** [comment] 2013-12-13 14:49
Yes, it still doesn't work for me. I am using the following:

```
spork (1.0.0rc4)
spork-rails (4.0.0)
```

**Comment by johnnyshields** [comment] 2013-12-13 14:51
Workaround: use Zeus.

**Comment by TheNaoX** [comment] 2013-12-17 22:49
:(

**Comment by Arcolye** [comment] 2013-12-27 17:56
I just installed Spork (+ guard) today, and I'm up against a bug that was first mentioned 2 years ago. Why closed?

**Comment by VeridionRO** [comment] 2014-03-15 17:49
I found an easy fix, just add this in your spec_helper, Spork.prefork:

Dir[Rails.root.join("spec/helpers/*.rb")].each { |f| require f }

Also remove "require 'spec_helper'" from your helpers it will cause an error if it's there
